* Hel — [[https://helix-editor.com/][Helix]] Emulation Layer for Emacs

** Key features

- Multiple cursors based modal editing inside Emacs!

- Undo/redo that plays well with multiple cursors.

- PCRE regexps by default (thanks to [[https://github.com/joddie/pcre2el][pcre2el]]).

- Smooth scrolling commands out of the box.

** Can I use Hel without knowing Emacs keys?

#+begin_quote
*Terminology note:* what Vim, Helix, and other modal editors call Normal and
Insert *modes*, Hel refers to as *states*. This is because the word "mode" in Emacs
is already used for its [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Major-Modes.html][major]] and [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Minor-Modes.html][minor]] modes.
#+end_quote

When several years ago I came to Emacs from Neovim, I was in love with Vim
editing model, found Emacs native keybindings ugly and had zero interest in
learning them. I want Emacs not as text editor (which it obviously lacks of)
but as an operation system with Lisp and all its power. So the first question
I asked myself was "Can I use Evil without learning Emacs keys?"

The answer is yes. I have never used — and still don’t know — most Emacs keys.
I know only a few that you need when something breaks early during Emacs startup
and you don’t have your Hel keys available. They are:

- =M-x= — Command palette. The main key you need; all other commands can be
  invoked from it.
- =C-x C-s= — Save current buffer.
- =C-x C-c= — Exit Emacs.

That’s it.

Hel and Emacs do not interfere much, because Emacs is not a modal editor:
letters and numbers are self-inserting, and most command key chords begin with
=C-x= or =C-c= (e.g. =C-x n d=). Due to this, Hel works as a layer on top of Emacs.

In Normal state you have selection-based editing, multiple cursors, and all the
other Hel features. In Insert state, Hel steps aside and standard Emacs keys
work as usual. Also Hel doesn't touch =C-x= and =C-c= so they are always available.
This allows you to mix Hel and Emacs in any proportion.

** Kakoune vs Helix

The main difference between Kakoune and Helix, in terms of text editing, is how
they handle expanding selections: Kakoune uses =Shift= + motions, while Helix uses
a separate state on the =v= key. Since I originally came from Vim, I prefer
Helix’s =v= key, so I chose Helix. However, Kakoune (as far as I know) was the
original inventor of this keyboard-driven multiple-selections approach, and it
deserves credit.

** Installation

Hel is not yet on MELPA. You can install it directly from Github using Emacs'
built-in package manager:

#+begin_src emacs-lisp
;; Dependencies
(use-package dash :ensure t)
(use-package avy :ensure t)
(use-package pcre2el :ensure t)

(use-package hel
  :vc (:url "https://github.com/anuvyklack/hel.git" :rev "main")
  :config (hel-mode))
#+end_src

** Documentation
- [[file:docs/keybindings.org][Keybindings]]
- [[file:docs/extensions.org][Extensions]]
- [[file:docs/customization.org][Customizations]]

** Differences from Helix text editor

This package is not one-to-one emulation. Some commands are implemented in
slightly different way (improved from the author's point of view), and some
features like keyboard macros, registers, and jumplists already have their
alternatives in Emacs.

- In Emacs the cursor ("point" in Emacs terms) is located *between* two characters
  rather than *on* a character like in Helix or Vim. I decided to keep this
  behavior, instead of emulating original one, as Evil does, because the primary
  object of interaction in Helix approach is a selection, not the cursor itself.

- =x= and =X= commands are reworked. They are expand and contract line-wise
  selection down when cursor is at the end of the selection, or up when cursor
  is at the beginning of the selection.

- Inner objects are additionally available directly under =m= prefix to reduce
  keystrokes: =mw= is the same as =miw= — select word.

- Mark commands accept numeric arguments:
  =m2ip= or =2mip= — select 2 paragraphs.

- =gh= / =gl= make a selection from current position till the beginning/end of the
  line. This is done for convenience, since all other motions make selections.
  In Helix =gh= / =gl= only move cursor without creating selection.

- Six easymotion commands are provided:
  - =gw= / =gb= — chose and mark word forward/backward.
  - =gW= / =gB= — chose and mark WORD forward/backward.
  - =gj= / =gk= — go to line down/up.
  Helix provides only =gw= to place 2-char hints at the beginning of each word.

- =gg= / =G= to go to the first/last line of the buffer like in Vim.
  Helix uses =gg= / =ge=.

- =f=, =F=, =t=, =T= commands to move to char are inhanced: they show hints for targets,
  and while hints are active, they can be repeated with =n= / =N= keys.

- When you search backward with =?= command, while hints are acitve =n= and =N= keys
  are swaped: =n= will repeat search backward and =N= — forward, like in Vim.

- Scrolling keybindings are taken from Vim instead of Helix.

** Commands that are not implemented

- =.= (repeat) — Need to decide what it should repeat.
- =r= — replace (TODO)
- =M-u=, =M-U= — traverse undo tree
- =q=, =Q= — record keyboard macros
  
** Acknowledgments

Hel depends on [[https://github.com/magnars/dash.el][dash.el]], [[https://github.com/joddie/pcre2el][pcre2el]], and [[https://github.com/abo-abo/avy][avy]] wonderful packages.

Hel is heavily inspired by:
- [[https://github.com/emacs-evil/evil][evil]]
- [[https://github.com/magnars/multiple-cursors.el][multiple-cursors.el]]
- [[https://github.com/aome510/kak.el][kak.el]]
- [[https://github.com/mkleehammer/surround][surround]]
- [[https://github.com/meow-edit/meow][meow]]
- [[https://github.com/doomemacs/doomemacs][doomemacs]]
- [[https://github.com/bbatsov/crux][crux]]

You are welcome to go and give them all at least a star!

** Contributing

- *Share it*

  A quick post about this package on your blog or social network could bring
  new users to Emacs, which would be great!

- *Support development*

  Hel was developed on an old laptop with a cracked screen. I worked on it instead
  of grinding LeetCode, and I have run out of money. If you like it and want to
  support its development, you can donate via:

  - [[https://www.paypal.me/anuvyklack][PayPal]]

  Every contribution is greatly appreciated. Thank you!
