#+title: Hell (Helix Emulation Layer)

[[https://helix-editor.com/][Helix Editor]] emulation layer. The name "Hell" was choosen to rhyme with [[https://github.com/emacs-evil/evil][Evil]].

* Differences from Helix text editor

- =gh= / =gl= make a selection from current position till the beginning/end of the
  line. This is done for convenience, since all other motions make selections.
  In Helix they only move cursor without selection.

- Inner objects are available directly under =m= prefix together with =mi= to reduce
  keystrokes: =mw= is the same as =miw= — select word.

- Match (or mark) commands accept numeric arguments:
  =m2ip= or =2mip= — mark 2 paragraphs.

- Right after search backward with =?= command, =n= and =N= are swaped: =n= will
  repeat search backward, =N= — forward, like in Vim.

* Known problems

- If command modify buffer only for some cursors, like ~helix-align-selection~
  does: it inserts spaces only in front of some selections to align them,
  then on undo cursors positions will desynchronize.
